data_path: /game_theoretic_NN/dataset/processed_sc2.pkl
model_path: /game_theoretic_NN/models/V_GT_sc2.pt
N: 10
##Not used for training. only used for visualization
type: test
input_normalization: False
one_hot_encoding: False
include_route: False 
hidden_size: 128
num_layers: 2
input_size: 6
